Pin python 3.11.9 to remove warnings, restyle Makefile, unpin pytest

diff --git a/python/Makefile b/python/Makefile
--- a/python/Makefile
+++ b/python/Makefile
@@ -1,18 +1,36 @@
-.PHONY: all clean docker-test docker-app user-service-drive
+.PHONY: all build-run-app build-run-test launch-drive docker-% clean
 
+# Default to testing
 all: docker-test clean
 
-clean:
-	docker rmi user-service-test || true
-	docker rmi user-service-app || true
+# Build and run a standalone containerized app
+build-run-app: docker-app
 
-docker-test:
-	docker build --target testing -t user-service-test .
-	docker run --rm user-service-test
+# Build and run containerized tests
+build-run-test: docker-test
 
-docker-app:
-	docker build --target standalone -t user-service-app .
-	docker run --rm -p 8000:8000 user-service-app
-
-user-service-drive:
+# Launch a drive test build-run-test must be running
+launch-drive:
 	python app_driver.py
+
+# Define the base image name
+BASE_IMAGE_NAME := user-service
+
+# Pattern rule for docker targets restricted to "test" or "app"
+docker-%:
+	@if [ "$*" = "test" ] || [ "$*" = "app" ]; then \
+		echo "Building and running target: $*"; \
+		docker build --target $* -t $(BASE_IMAGE_NAME)-$* .; \
+		docker run --rm $(BASE_IMAGE_NAME)-$*; \
+	else \
+		echo "Invalid target: $*. Only 'test' and 'app' are allowed."; \
+		exit 1; \
+	fi
+
+# Clean target to remove created Docker images
+clean:
+	@docker image inspect $(BASE_IMAGE_NAME)-test > /dev/null 2>&1 && \
+	docker rmi user-service-test || true
+
+	@docker image inspect $(BASE_IMAGE_NAME)-test-app > /dev/null 2>&1 && \
+	docker rmi user-service-app || true
